//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListadoMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int idCancion { get; set; }
        public string titulo { get; set; }
        public string artista { get; set; }
        public string año { get; set; }
        public string genero { get; set; }
        public int estatus { get; set; }
        public int idUsuarioAgrega { get; set; }
        public Nullable<System.DateTime> fechaAgrega { get; set; }
        public Nullable<int> idUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
